### PR TITLE
Add methods document

### PR DESCRIPTION
**Pull request by dcb9**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues |  |

### CODE REVIEW

**Comment by cebe** [comment]
thank you! did you use a script for this or did you do it manually?

**Comment by samdark** [comment]
These are much better than nothing but still incorrect about parameters and return types.

**Comment by cebe** [comment]
sure, but if there was a script I'd take it and adjust it.

**Comment by dcb9** [comment]
I used vim macro. based on `Connection::$redisCommands`

in vim `:registers`

`"a   0vi'~0s@method mixed ^[f'vf/;s()^[j`

trtnsx

**Comment by cebe** [comment]
fixed by https://github.com/yiisoft/yii2-redis/commit/882fb022c6c5a3721b14d5949abbb0e4c3d8353f which provides more complete phpdoc info including parameters. Thanks for your contribution!

**Pull request closed without merging**
