### PR TITLE
Attempt to fix tests

### PR DESCRIPTION
**Pull request by sergeymakinen**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Note this weird stuff: https://github.com/yiisoft/yii2-redis/blob/master/tests/bootstrap.php#L17. 

@cebe explained why:

> phpunit is pre-installed on travis and we relied on that to not download the whole dependency tree on each build. Seems to break now with phpunit 6.
> 
> It is so weird, because it uses the test classes from framework when installed in the way it was before we split out extensions. but on standalone it will download the files from framework.
>
> We should clean that up at some point.

**Comment by sergeymakinen** [comment]
I see that Travis pushed PHP 7.0.16 with PHPUnit 6 which removed all global classes. It also looks like that not all nodes are updated so it will break other extensions if they don’t stick with PHPUnit 4.8/5.x.
(Although I made a universal BC compatible wrapper for my extensions (4.8/5.x/6.x)

**Comment by samdark** [comment]
Oh. Wasn't aware about different images on different nodes.

**Comment by sergeymakinen** [comment]
Ok. Fixed & squashed.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
