### PR TITLE
Fix reconnect to Redis

### PR DESCRIPTION
**Pull request by kshart**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #176

### CODE REVIEW

**Comment by samdark** [comment]
@cebe would you please take a look?

**Comment by rob006** [comment]
Tests are failing. And to be honest, these changes do not make any sense to me. And I don't understand problem reported in #176 - there are tests to verify `retries` support, if something is wrong with the behavior, we should start from changing tests to show what is wrong. Right now tests are passing on master and failing on this PR, so basically, this PR is breaking stuff :P.

**Comment by kshart** [comment]
@rob006 Hi, I do not know how to make `service redis stop/start` or `ifdown/ifup` in the test. The problem occurs when "operating system" breaks the link

**Comment by cebe** [comment]
This change does not solve the problem but moves it to another method making the direct method call unable to retry. I'm closing this pull request, the issue however is valid. See my comment there.

**Pull request closed without merging**
