### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by pana1990**

### CODE REVIEW

**Comment by SilverFire** [comment]
@pana1990 thank you for your contribution. I think we should just remote that lines, instead of commenting the out. What do you think?

**Comment by pana1990** [comment]
i did copy/paste from https://github.com/yiisoft/yii2/blob/master/.travis.yml#L15

your propositional is ok for me.

**Comment by pana1990** [comment]
@SilverFire  ready to merge

**Comment by SilverFire** [comment]
Thank you!

**Pull request merged**
