### PR TITLE
Fix the escape bug.

### PR DESCRIPTION
**Pull request by vistart**
Fix the escape bug.
See detail in https://github.com/yiisoft/yii2-redis/issues/22

### CODE REVIEW

**Comment by vistart** [comment]
Why were these merged into #27 ?

**Comment by cebe** [comment]
because you are working on the master branch. for sending different changes in different PRs you should create different branches.

**Comment by vistart** [comment]
I see. What should I do next? Revert to 7b40fb5? Then create new branche named as "Translation in Simplified Chinese"?

**Comment by cebe** [comment]
No need for that, I can do that myself when merging.

**Comment by vistart** [comment]
OK.

**Comment by cebe** [comment]
merged, thank you!

**Pull request closed without merging**
