### PR TITLE
PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by brandonkelly**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by samdark** [comment]
7.2 should be added to `.travis.yml` in order to make sure it works well.

**Comment by brandonkelly** [comment]
@samdark done 👍

**Comment by samdark** [comment]
Tests do fail. This is additional case to be fixed where `count()` should be called on objects only.

**Comment by brandonkelly** [comment]
@samdark Fixed now, and Travis likes it.

**Pull request merged**
