### PR TITLE
Yiisoft

### PR DESCRIPTION
**Pull request by nailfor**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #13

### CODE REVIEW

**Comment by zacksleo** [comment]
Why are there so many changes?

**Comment by zacksleo** [comment]
Why are there so many changes?

**Comment by nailfor** [comment]
I don't know. I'm pull request only for issue #13, but here is full my branch, it incompatible with current yii2-redis, because i'm use SADD, SCARD, SMEMBERS

**Comment by zacksleo** [comment]
So can you checkout a new branch just from the commit "issue #13" and make a new PR ?

**Comment by nailfor** [comment]
yes, i can..
But my branch has gone a far away, and it's easier for me simply get yii2-redis, fork it, and apply some changes.

**Comment by zacksleo** [comment]
I am very grateful that you can do that. This feature game me a great favor so I hope this can be merged in to the official repository.

**Comment by nailfor** [comment]
I did new PR

**Pull request closed without merging**
