### PR TITLE
Move application code to "src" directory

### PR DESCRIPTION
**Pull request by zhukovra**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

Move source files to "src" directory. Discussed in https://github.com/yiisoft/yii2-httpclient/pull/140
Updated Travis configuration file.

### CODE REVIEW

**Comment by zhukovra** [comment]
@cebe what are you think about it?

**Comment by samdark** [comment]
It's OK but needs more polishing such as https://github.com/yiisoft/yii2-authclient/commit/829d298cfd9f6e1dd8fd52d7b7e2ffc0ccbc36d7

**Comment by zhukovra** [comment]
@samdark I don't understand [line](https://github.com/yiisoft/yii2-authclient/blob/52325938e90bb3a1f8ca72c7192f11feb612cdd6/tests/bootstrap.php#L15) with `setAlias('@yii/authclient', dirname(__DIR__).'/src')` at all because namespace already was registered [in composer.json](https://github.com/yiisoft/yii2-authclient/blob/52325938e90bb3a1f8ca72c7192f11feb612cdd6/composer.json#L33). Please help me - what is purpose of this line? Or maybe @klimov-paul can explain. Thank you.

So I've just removed it from `bootstrap.php`. As you can see - it passes tests.

**Comment by samdark** [comment]
That's directory name, not namespace.

**Comment by zhukovra** [comment]
Your comment does not answer on question about the purpose of setting alias :disappointed: Please help me with that puzzle.

**Comment by samdark** [comment]
That is for the case someone will have any resource accessed via `Yii::getAlias('@yii/authclient/something.txt')`. As far as I'm aware it's the only purpose. In case of authclient there are asset bundles that may use that.

**Comment by zhukovra** [comment]
From my point of view - every line of code must be necessary or you commit just for entropy raising :boom: :laughing:  
If tests work without the line - that line is useful.

**Comment by samdark** [comment]
Yup. Merged.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
